print(1)
print(1, 2)
print(1, 2, "ab")
print(1, 2, "ab", [1, 2, "a", [1, 2, 3]])
print("Mr", "I")
x = input("Enter a number: ")
y = input("Enter another number: ")
print(x)
print(y)

print(x, y, "Why!")
